# Generated by Django 3.2.9 on 2021-12-17 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField()),
                ('gender', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('allergies', models.TextField(blank=True, null=True)),
                ('existing_conditions', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.breed')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
