# Generated by Django 3.2.9 on 2021-12-22 08:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211222_0727'),
        ('livestock', '0002_animalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookVet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specialization')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vet')),
            ],
        ),
    ]
